//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceptPolicySpec) DeepCopyInto(out *AcceptPolicySpec) {
	*out = *in
	if in.ISDASes != nil {
		in, out := &in.ISDASes, &out.ISDASes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenCIDRs != nil {
		in, out := &in.ForbiddenCIDRs, &out.ForbiddenCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UnderlayCIDRs != nil {
		in, out := &in.UnderlayCIDRs, &out.UnderlayCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceptPolicySpec.
func (in *AcceptPolicySpec) DeepCopy() *AcceptPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AcceptPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertisementSpec) DeepCopyInto(out *AdvertisementSpec) {
	*out = *in
	if in.PodCIDR != nil {
		in, out := &in.PodCIDR, &out.PodCIDR
		*out = new(bool)
		**out = **in
	}
	if in.NodeIP != nil {
		in, out := &in.NodeIP, &out.NodeIP
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertisementSpec.
func (in *AdvertisementSpec) DeepCopy() *AdvertisementSpec {
	if in == nil {
		return nil
	}
	out := new(AdvertisementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSpec) DeepCopyInto(out *BootstrapSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSpec.
func (in *BootstrapSpec) DeepCopy() *BootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataplaneSpec) DeepCopyInto(out *DataplaneSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataplaneSpec.
func (in *DataplaneSpec) DeepCopy() *DataplaneSpec {
	if in == nil {
		return nil
	}
	out := new(DataplaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSummary) DeepCopyInto(out *NodeSummary) {
	*out = *in
	if in.Degraded != nil {
		in, out := &in.Degraded, &out.Degraded
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSummary.
func (in *NodeSummary) DeepCopy() *NodeSummary {
	if in == nil {
		return nil
	}
	out := new(NodeSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistrarSpec) DeepCopyInto(out *RegistrarSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistrarSpec.
func (in *RegistrarSpec) DeepCopy() *RegistrarSpec {
	if in == nil {
		return nil
	}
	out := new(RegistrarSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistrarStatus) DeepCopyInto(out *RegistrarStatus) {
	*out = *in
	if in.DesiredSIGs != nil {
		in, out := &in.DesiredSIGs, &out.DesiredSIGs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistrarStatus.
func (in *RegistrarStatus) DeepCopy() *RegistrarStatus {
	if in == nil {
		return nil
	}
	out := new(RegistrarStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScionNetwork) DeepCopyInto(out *ScionNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScionNetwork.
func (in *ScionNetwork) DeepCopy() *ScionNetwork {
	if in == nil {
		return nil
	}
	out := new(ScionNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScionNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScionNetworkList) DeepCopyInto(out *ScionNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScionNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScionNetworkList.
func (in *ScionNetworkList) DeepCopy() *ScionNetworkList {
	if in == nil {
		return nil
	}
	out := new(ScionNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScionNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScionNetworkSpec) DeepCopyInto(out *ScionNetworkSpec) {
	*out = *in
	in.Bootstrap.DeepCopyInto(&out.Bootstrap)
	in.Advertisement.DeepCopyInto(&out.Advertisement)
	in.AcceptPolicy.DeepCopyInto(&out.AcceptPolicy)
	out.Dataplane = in.Dataplane
	in.Registrar.DeepCopyInto(&out.Registrar)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScionNetworkSpec.
func (in *ScionNetworkSpec) DeepCopy() *ScionNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(ScionNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScionNetworkStatus) DeepCopyInto(out *ScionNetworkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Nodes.DeepCopyInto(&out.Nodes)
	in.Registrar.DeepCopyInto(&out.Registrar)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScionNetworkStatus.
func (in *ScionNetworkStatus) DeepCopy() *ScionNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(ScionNetworkStatus)
	in.DeepCopyInto(out)
	return out
}
